### ISSUE TITLE
image upload UI (enhancement)

### ISSUE THREAD

**Issue by swongg** [0xla/cpsc455-project#57]
- image upload should allow users to add an image description as well
- drag and drop UI component

**Comment by snow2650** [comment]
How is this part now? My version still has a lot of bugs. Do you want to check it or we can do this together.

**Comment by swongg** [comment]
> How is this part now? My version still has a lot of bugs. Do you want to check it or we can do this together.

Hey Esther, I will look for a pre-made component for this so it should be fine for now
